name: CI Status

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Success Notification
        run: |
          echo "✅ CI Pipeline Successful!"
          echo "Commit: ${{ github.event.workflow_run.head_sha }}"
          echo "Branch: ${{ github.event.workflow_run.head_branch }}"
  
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Failure Notification
        run: |
          echo "❌ CI Pipeline Failed!"
          echo "Commit: ${{ github.event.workflow_run.head_sha }}"
          echo "Branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Check the logs at: ${{ github.event.workflow_run.html_url }}"